title: Vatsal | Data Analyst Portfolio
email: 12.vatsal09@gmail.com
description: Aspiring Data Analyst/Scientist skilled in Python, SQL, Tableau, and Excel.
baseurl: ""
url: "https://vatsalsrivastava1209.github.io"
theme: jekyll-theme-persephone